import type { Lang, Project } from "../CV/cv_content";
export type Kind = "web" | "mobile" | "bot" | "hardware";
export type Context = "personal" | "course" | "team";
export type Status = "ongoing" | "wip" | "finished";
export type AiUse = "none" | "assisted" | "generated";
type Bilingual = {
    en: string;
    no: string;
};
export type ProjectMeta = {
    kind: Kind;
    context: Context;
    course?: string;
    status: Status;
    ai?: AiUse;
    aiNote?: Bilingual;
    team?: number;
    role?: Bilingual;
    period?: Bilingual;
    links?: {
        label: Bilingual;
        url: string;
    }[];
    images?: string[];
    sections?: {
        title: Bilingual;
        body: Bilingual;
    }[];
    extraTags?: string[];
};
export declare const projectMeta: Record<string, ProjectMeta>;
export type MergedProject = Project & {
    slug: string;
    meta: ProjectMeta;
};
export declare function getProjects(lang: Lang): MergedProject[];
export type Ui = {
    backToSite: string;
    allProjects: string;
    allHeading: string;
    navCv: string;
    navRun: string;
    navProjects: string;
    title: string;
    intro: string;
    projectsCount: string;
    fromCourses: string;
    madeWithAi: string;
    filter: string;
    projectType: string;
    showing: string;
    empty: string;
    all: string;
    kinds: Record<Kind, string>;
    toggleAi: string;
    toggleCourse: string;
    toggleTeam: string;
    togglePersonal: string;
    contexts: Record<Context, string>;
    statuses: Record<Status, string>;
    aiBadge: Record<"assisted" | "generated", string>;
    aiUse: Record<AiUse, string>;
    aiUseLabel: string;
    readMore: string;
    readMoreAria: (name: string) => string;
    solo: string;
    students: (n: number) => string;
    facts: string;
    tech: string;
    type: string;
    context: string;
    team: string;
    role: string;
    period: string;
    status: string;
    links: string;
    overview: string;
    screens: string;
    howAi: string;
    screenshot: (name: string, n: number) => string;
    prevNext: string;
    other: string;
};
export declare const ui: Record<Lang, Ui>;
export declare function contextLabel(t: Ui, meta: ProjectMeta): string;
export declare function teamLabel(t: Ui, team: number): string;
export declare function isTeam(meta: ProjectMeta): boolean;
export declare function usesAi(meta: ProjectMeta): boolean;
export {};
